const places = [
  {id:'gwanghwamun',name:'Gwanghwamun',korean:'광화문',kind:'Porta principale',lat:37.57590,lng:126.97684,era:'1395 · ricostruita nel 2010',minutes:3,story:'La soglia monumentale del palazzo e il punto in cui la città incontra la corte reale.',detail:'Il nome significa “Porta della trasformazione luminosa”. Era l’ingresso meridionale al palazzo principale dei Joseon. Distrutta e spostata più volte, è tornata sul suo asse storico con la ricostruzione completata nel 2010.'},
  {id:'heungnyemun',name:'Heungnyemun',korean:'흥례문',kind:'Seconda porta',lat:37.57718,lng:126.97691,era:'Area cerimoniale',minutes:2,story:'Qui il percorso rallenta: oltre la porta iniziava il mondo regolato della corte.',detail:'Il cortile fra Gwanghwamun e Heungnyemun fu profondamente alterato nel periodo coloniale. La porta odierna fa parte del lungo progetto di recupero dell’assetto storico del palazzo.'},
  {id:'geunjeongjeon',name:'Geunjeongjeon',korean:'근정전',kind:'Sala del trono',lat:37.57863,lng:126.97688,era:'Tesoro nazionale · 1867',minutes:5,story:'Il cuore politico della dinastia: incoronazioni, udienze e grandi cerimonie di Stato.',detail:'Osserva le pietre di rango nel cortile: indicavano dove dovevano disporsi i funzionari. Il padiglione attuale risale alla grande ricostruzione del 1867 e conserva la solennità dell’architettura reale Joseon.'},
  {id:'sajeongjeon',name:'Sajeongjeon',korean:'사정전',kind:'Ufficio del re',lat:37.57930,lng:126.97690,era:'1395 · ricostruita nel 1867',minutes:4,story:'Non solo cerimonie: qui il sovrano lavorava ogni giorno con i suoi ministri.',detail:'Sajeongjeon significa “Sala del governo ponderato”. Era il principale spazio di lavoro quotidiano del re. Gli edifici laterali avevano il riscaldamento ondol e risultavano più confortevoli in inverno.'},
  {id:'gyeonghoeru',name:'Gyeonghoeru',korean:'경회루',kind:'Padiglione sul lago',lat:37.57970,lng:126.97510,era:'Tesoro nazionale · 1867',minutes:6,story:'Un’isola cerimoniale sull’acqua, costruita per banchetti reali e ospiti diplomatici.',detail:'Il padiglione si alza su 48 colonne di pietra. La superficie riflettente dello stagno e il profilo del monte Bugaksan trasformano il paesaggio in una scenografia del potere reale.'},
  {id:'gangnyeongjeon',name:'Gangnyeongjeon',korean:'강녕전',kind:'Residenza del re',lat:37.58002,lng:126.97692,era:'Quartiere privato',minutes:4,story:'La vita privata del sovrano iniziava qui, dietro le sale ufficiali.',detail:'Era la camera e residenza principale del re. Il tetto è privo della grande trave di colmo decorata: secondo la tradizione, nessun simbolo di drago poteva sovrastare il re, lui stesso associato al drago.'},
  {id:'gyotaejeon',name:'Gyotaejeon',korean:'교태전',kind:'Residenza della regina',lat:37.58054,lng:126.97693,era:'Quartiere privato',minutes:4,story:'La residenza della regina e centro della vita della famiglia reale.',detail:'Dietro la sala si trova Amisan, un giardino a terrazze creato con la terra scavata per lo stagno di Gyeonghoeru. I camini decorati uniscono funzione, simbolismo e paesaggio.'},
  {id:'hyangwonjeong',name:'Hyangwonjeong',korean:'향원정',kind:'Padiglione del loto',lat:37.58255,lng:126.97675,era:'c. 1873',minutes:5,story:'Il volto più intimo del palazzo: un padiglione esagonale sospeso tra acqua e loto.',detail:'Il nome evoca una “fragranza che arriva lontano”. Il ponte Chwihyanggyo conduce all’isola; l’insieme fu creato durante il regno di Gojong come luogo di riposo nel settore settentrionale.'},
  {id:'geoncheonggung',name:'Geoncheonggung',korean:'건청궁',kind:'Residenza reale',lat:37.58310,lng:126.97730,era:'1873 · ricostruita nel 2007',minutes:7,story:'Una residenza quasi domestica, legata agli ultimi anni drammatici della corte.',detail:'Costruita per re Gojong e la regina Myeongseong, adottava lo stile di una casa aristocratica. Nel vicino Gonnyeonghap la regina fu assassinata nel 1895, evento decisivo nella crisi della Corea di fine Ottocento.'},
  {id:'jibokjae',name:'Jibokjae',korean:'집옥재',kind:'Biblioteca reale',lat:37.58215,lng:126.97810,era:'Fine XIX secolo',minutes:4,story:'Una biblioteca reale dall’insolito linguaggio architettonico di influenza cinese.',detail:'Gojong la usò come biblioteca e sala di ricevimento. Le facciate in mattoni e le decorazioni la distinguono nettamente dai padiglioni lignei che scandiscono il resto del palazzo.'}
];
const bounds={north:37.5840,south:37.57535,west:126.97425,east:126.97865};
let selected='geunjeongjeon', locationData=null, sheetOpen=true;
const $=id=>document.getElementById(id);
function distance(a,b){const r=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function pos(lat,lng){return{left:`${(lng-bounds.west)/(bounds.east-bounds.west)*100}%`,top:`${(bounds.north-lat)/(bounds.north-bounds.south)*100}%`};}
function choose(id){selected=id;sheetOpen=true;render();$('storySheet').scrollIntoView({behavior:'smooth',block:'center'});}
function render(){
  const p=places.find(x=>x.id===selected), index=places.indexOf(p), d=locationData?Math.round(distance(locationData,p)):null;
  document.querySelectorAll('.marker').forEach(el=>el.classList.toggle('selected',el.dataset.id===selected));
  $('eyebrow').textContent=d===null?p.kind:`A ${d} m da te`;$('placeName').textContent=p.name;$('placeMeta').textContent=`${p.korean} · ${p.era}`;
  $('stopNumber').innerHTML=`${index+1}<small>/10</small>`;$('placeStory').textContent=p.story;$('placeDetail').textContent=p.detail;$('duration').textContent=`⏱ ${p.minutes} min`;
  $('storySheet').className=`storySheet ${sheetOpen?'open':'closed'}`;$('sheetHandle').setAttribute('aria-label',sheetOpen?'Riduci scheda':'Apri scheda');
  $('routeTitle').textContent=locationData?'Vicino a te':'Percorso consigliato';renderList();
}
function renderList(){const ordered=locationData?[...places].sort((a,b)=>distance(locationData,a)-distance(locationData,b)):places;$('placeList').innerHTML='';ordered.forEach(p=>{const b=document.createElement('button');b.className=selected===p.id?'active':'';b.innerHTML=`<span class="listNum">${places.indexOf(p)+1}</span><span class="listText"><b>${p.name}</b><small>${p.korean} · ${p.kind}</small></span><span class="distance">${locationData?Math.round(distance(locationData,p))+' m':p.minutes+' min'} ›</span>`;b.onclick=()=>choose(p.id);$('placeList').appendChild(b);});}
function buildMap(){places.forEach((p,i)=>{const b=document.createElement('button');b.className='marker';b.dataset.id=p.id;b.setAttribute('aria-label',p.name);Object.assign(b.style,pos(p.lat,p.lng));b.innerHTML=`<span>${i+1}</span><em>${p.name}</em>`;b.onclick=()=>choose(p.id);$('mapArea').appendChild(b);});}
function locate(){
  if(!navigator.geolocation){showError('La geolocalizzazione non è disponibile in questo browser.');return;}
  $('gpsButton').className='gpsButton loading';$('gpsLabel').textContent='Cerco…';
  navigator.geolocation.getCurrentPosition(g=>{locationData={lat:g.coords.latitude,lng:g.coords.longitude,accuracy:g.coords.accuracy};$('gpsButton').className='gpsButton active';$('gpsLabel').textContent='Posizione attiva';$('locationPrompt').textContent='Ti mostro il luogo più vicino';const closest=places.reduce((a,b)=>distance(locationData,a)<distance(locationData,b)?a:b);selected=closest.id;drawUser();render();$('mapArea').scrollIntoView({behavior:'smooth',block:'center'});},()=>showError('Non riesco a leggere il GPS. Puoi esplorare toccando i punti sulla mappa.'),{enableHighAccuracy:true,timeout:12000,maximumAge:5000});
}
function drawUser(){document.querySelector('.userPin')?.remove();const inside=locationData.lat>=bounds.south&&locationData.lat<=bounds.north&&locationData.lng>=bounds.west&&locationData.lng<=bounds.east;if(!inside){showError('Sei fuori dal perimetro del palazzo. La mappa resta esplorabile manualmente.');return;}const pin=document.createElement('div');pin.className='userPin';Object.assign(pin.style,pos(locationData.lat,locationData.lng));pin.innerHTML='<span></span><i>Tu sei qui</i>';$('mapArea').appendChild(pin);$('notice').hidden=true;}
function showError(text){$('notice').textContent=text;$('notice').hidden=false;$('gpsButton').className='gpsButton';$('gpsLabel').textContent='Riprova';$('locationPrompt').textContent='Esplora la mappa manualmente';}
$('gpsButton').onclick=locate;$('sheetHandle').onclick=()=>{sheetOpen=!sheetOpen;render();};$('listenButton').onclick=()=>{if(!('speechSynthesis' in window))return showError('L’audioguida non è disponibile in questo browser.');const p=places.find(x=>x.id===selected),utterance=new SpeechSynthesisUtterance(`${p.name}. ${p.story} ${p.detail}`);utterance.lang='it-IT';speechSynthesis.cancel();$('listenButton').classList.add('speaking');utterance.onend=()=>$('listenButton').classList.remove('speaking');speechSynthesis.speak(utterance);};
buildMap();render();
